### ISSUE TITLE
custom_security_conf example does not work with spring boot 3

### ISSUE THREAD

**Issue by Chip3211** [bratkartoffel/security-jwt-examples#3]
The superclass `WebSecurityConfigurerAdapter` used in [CustomSecurityConfig.java](https://github.com/bratkartoffel/security-jwt-examples/blob/master/starter-custom-security-conf/src/main/java/eu/fraho/spring/example/starter_custom_security_conf/CustomSecurityConfig.java) doesn't exist anymore in Spring Boot 3.

**Comment by bratkartoffel** [comment]
Yes, that's why the project is excluded when Spring Boot 3 is used (https://github.com/bratkartoffel/security-jwt-examples/blob/master/settings.gradle#L5)

Haven't found time to write another example using the new way. But as this is completely independent from my `security-jwt` library I even thought about removing this example sub-project.
